language: cpp
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
dist: trusty
osx_image: xcode7.3
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - binutils-dev
      - g++-4.7
env:
  global:
    - secure: Xj8vvg++O4mhcUTQGtHqXHhn8o5LklI/GkGWO6fcRXlJQszvpSMQiYfJ1UAYlmmuvXRNjWWdhEr7inJdHe1ZtNSXVU/jEICUytFBG6T3uuhOsBPkjVTp2en5vwsSPohaHcAnhoDyK9L48SBcTKLTCkTMhOitj9jk2renem0dX84=
    - secure: hlvi4mjZROjf/qaeh7qiyePyoyuoQXrvsiW6hrnWbu8u+vnI9QIay/9Wuxj+UBuUn4c8bUe37rrqn7mj2x8jbxNeq/i5RCTP6FOxqj7Q9b0xwBKYkygLnsYwgh5woefR5xeP9kzpIj449M5qWFjj926bpBLmO/YXrqV75ZD1vWPtPYiv2q/dUHMFVlspR5qK3SjiWK21XvdgAsj0VbUiQrO1I4G3vQRSNawvlA6VJN7S0sia3QQjYG0/l1INkykbACm7FIE7j8ABGVWuZUra+gisKnmUEMk/MwljMcAhssk2CHJKNj3Gj7meEP3Mk+JEx7HCnXoGTHk91BoGFLL2dBJgHf7d87G2+SFYKgp01qWonU3WC/hEs/l4nnLWNNCTElZ2afoiZqnuCeCQm7K7BkvhNXuunyvoaoDwtNJqvxMVAajzWqFdrSTqFTwgmxkX0VP58BXNl+IT0dCtA41xmncw6NSCejt4KiW/HZea0nJxFr5jkDDbKsyoKb9v+RkSe6yhCjA0wLFcP4isIPgmayIhPsvYmBELG2BE3v9QcEZVynijLHDUl9cTATq+0XpT/srBmynpPtURxbNByeoAXJdYGZLf+fKf8JbF5CQD5ylEGz4wlxbCIvzi8pFxXv1j3z159SSQYnGJsc5QMuZ7+1tScSIcK42bFnP3Z5POimA=
  matrix:
    - BUILD_TYPE="Debug" WITH_BFD="yes"
    - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_SYMENGINE_THREAD_SAFE="yes"
    - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_ECM="yes" WITH_PRIMESIEVE="yes" WITH_MPC="yes"
    - BUILD_TYPE="Debug" WITH_BFD="yes" WITH_ARB="yes" INTEGER_CLASS="flint" WITH_MPC="yes"
      BUILD_DOXYGEN="yes" TEST_IN_TREE="yes"
    - BUILD_TYPE="Debug" WITH_SYMENGINE_RCP="yes" WITH_MPFR="yes" INTEGER_CLASS="gmpxx"
    - BUILD_TYPE="Debug" WITH_BFD="yes" INTEGER_CLASS="boostmp"
    - BUILD_TYPE="Debug" WITH_BFD="yes" BUILD_SHARED_LIBS="yes"
    - WITH_BFD="yes"
    - WITH_BFD="yes" BUILD_SHARED_LIBS="yes"
    - BUILD_TYPE="Debug" WITH_BFD="yes" TEST_IN_TREE="yes"
matrix:
  exclude:
    - compiler: clang
    - os: osx
  include:
    - env:
        BUILD_TYPE="Debug" WITH_BFD="yes" WITH_LATEST_GCC="yes" WITH_COVERAGE="yes"
        WITH_MPC="yes" WITH_LLVM="8.0" USE_GLIBCXX_DEBUG="yes"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
            - llvm-8-dev
            - binutils-dev
            - g++-8
    - env: TEST_CLANG_FORMAT="yes"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-format-3.8
      install:
        - echo "nothing to install"
      script:
        - bin/travis_clang_format.sh
    - env:
        BUILD_TYPE="Debug" WITH_BFD="yes" WITH_GCC_6="yes" WITH_PIRANHA="yes" MAKEFLAGS="-j2"
        BUILD_SHARED_LIBS="yes"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - binutils-dev
            - g++-6
    - env:
        BUILD_TYPE="Debug" WITH_BFD="yes" WITH_COVERAGE="yes" TEST_IN_TREE="yes"
        WITH_FLINT="yes" WITH_FLINT_DEV="yes" WITH_MPC="yes" BUILD_BENCHMARKS="no" MAKEFLAGS="-j2"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - binutils-dev
            - g++-4.7
    - env:
        BUILD_TYPE="Debug" WITH_BFD="yes" WITH_PIRANHA="yes" INTEGER_CLASS="piranha"
        MAKEFLAGS="-j2"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - binutils-dev
            - g++-4.8
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_LLVM="6.0" WITH_BENCHMARKS_NONIUS="yes"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libstdc++-4.8-dev
            - libgmp-dev
            - binutils-dev
            - llvm-6.0-dev
    - env: BUILD_TYPE="Release"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - libstdc++-4.8-dev
            - libgmp-dev
    - env: BUILD_TYPE="Debug" WITH_LLVM="3.8"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Release" WITH_LLVM="5.0"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Debug"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Debug" WITH_SANITIZE="address" WITH_LLVM="7.0"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - llvm-7-dev
    - env: BUILD_TYPE="Debug" WITH_SANITIZE="undefined" WITH_LLVM="7.0"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - llvm-7-dev
    - env:
        BUILD_TYPE="Debug" WITH_SYMENGINE_RCP="yes" WITH_BFD="no" WITH_SANITIZE="memory"
        INTEGER_CLASS="boostmp"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - llvm-7-dev
    - env: CONDA_ENV_FILE="binder/environment.yml"
      compiler: gcc
      os: linux
      script:
        - bin/test_cling_notebook.sh
    - env: CONDA_ENV_FILE="symengine/utilities/matchpycpp/environment.yml"
      compiler: gcc
      os: linux
      script:
        - bin/test_matchpycpp_gen_tests.sh
before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      command curl -sSL https://rvm.io/mpapis.asc | gpg --import -;
      rvm get head || true
    fi
install:
  - source bin/install_travis.sh
script:
  - bin/test_travis.sh
  - bin/trigger_feedstock.sh
  - bin/trigger_docs.sh
notifications:
  email: false
